moj:
  server:
    assignment-repo: /data/assignments
    performance-validation: true
    languages:
      java-versions:
        - version: 11
          name: Java 11
          compiler: /opt/java/openjdk/bin/javac
          runtime: /opt/java/openjdk/bin/java
    directories:
      team-directory: teams
      lib-directory: lib
      sound-directory: sounds
      javadoc-directory: javadoc
      base-directory: /data/moj-data
    limits:
      compile-timeout: PT4S
      compile-output-limits:
        max-feedback-lines: 1000
        max-chars: 100000
        max-line-len: 1000
        line-truncated-message: "...{truncated}"
        output-trunc-message: "...{output truncated}"
        timeout-message: "...{terminated: compile time expired}"
      test-timeout: PT4S
      test-output-limits:
        max-feedback-lines: 1000
        max-chars: 100000
        max-line-len: 1000
        line-truncated-message: "...{truncated}"
        output-trunc-message: "...{output truncated}"
        timeout-message: "...{terminated: test time expired}"
    runtime:
      game-threads: 10
    competition:
      uuid: 77eff9b5-46cb-4420-bddf-fea52716fc6a
      success-bonus: 400

keycloak:
  auth-server-url: https://auth.moj.first8.nl/auth
  realm: moj
  resource: moj
  public-client: true
  principal-attribute: subject

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/data/db/moj
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  thymeleaf:
    mode: HTML
  flyway:
    enabled: true
    baseline-on-migrate: true
  resources:
    static-locations: classpath:/bootstrap/sounds/,classpath:/static/
#  jpa:
#    generate-ddl: true

server:
  forward-headers-strategy: native

logging.level.nl.moj.server: DEBUG

logging.level.nl.moj.server.persistence: INFO
logging.level.nl.moj.server.persistence.TeamMapper: INFO
logging.level.nl.moj.server.persistence.ResultMapper: INFO
logging.level.org.springframework.integration.file.FileReadingMessageSource: FATAL
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.security: DEBUG
logging.level.org.keycloak: DEBUG
logging.level.org.apache.catalina.valves.RemoteIpValve: DEBUG
